apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: my-app-namespace
spec:
  selector:
    app: chat-service
  ports:
  - protocol: TCP
    port: 7100
    targetPort: 7100
  type: ClusterIP