apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: my-app-namespace
spec:
  selector:
    app: users-service
  ports:
  - protocol: TCP
    port: 7101
    targetPort: 7101
  type: ClusterIP