apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: my-app-namespace
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 32000
