apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: imzainazm/api-gateway:latest
        ports:
        - containerPort: 7000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "250m"
