apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: imzainazm/chat-service
        ports:
        - containerPort: 7100
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "250m"
