apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chat-service-db
  namespace: my-app-namespace
spec:
  serviceName: "chat-service-db"
  replicas: 1
  selector:
    matchLabels:
      app: chat-service-db
  template:
    metadata:
      labels:
        app: chat-service-db
    spec:   
      containers:
      - name: mysql
        image: mysql:5.7.20
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
