apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-service-db
spec:
  serviceName: "users-service-db"
  replicas: 1
  selector:
    matchLabels:
      app: users-service-db
  template:
    metadata:
      labels:
        app: users-service-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.20
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "250m"
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
