apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
  namespace: my-app-namespace
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
      nodePort: 32005