chatApp:
  name: chat-app
  namespace: my-app-namespace-3
  replicas: 1
  containerName: chat-app
  image:
    repository: imzainazm/chat-app
    tag: latest
  containerPort: 7001
  labels:
    environment: staging
  service:
    name: chat-app-service
    type: NodePort
    port: 7001
    targetPort: 7001
    nodePort: 32001
  configMap:
    name: app-config
    key: API_GATEWAY_URI
    apiGatewayUri: "api-gateway-service:7000"


namespace: my-app-namespace-3

secret: 
  name: my-secret
  type: Opaque
