apiGateway:
  name: api-gateway
  namespace: my-app-namespace-3
  replicas: 1
  containerName: api-gateway
  image:
    repository: imzainazm/api-gateway
    tag: latest
  containerPort: 7000
  service:
    name: api-gateway-service
    type: NodePort
    port: 7000
    targetPort: 7000
    nodePort: 32000

chatApp:
  name: chat-app
  namespace: my-app-namespace-3
  replicas: 1
  containerName: chat-app
  image:
    repository: imzainazm/chat-app
    tag: latest
  containerPort: 7001
  service:
    name: chat-app-service
    type: NodePort
    port: 7001
    targetPort: 7001
    nodePort: 32001
  configMap:
    name: app-config
    key: API_GATEWAY_URI
    apiGatewayUri: "http://172.29.25.105:32000"

chatServiceDb:
  name: chat-service-db
  namespace: my-app-namespace-3
  replicas: 1
  selector:
    app: chat-service-db
  containerName: mysql
  image:
    repository: mysql
    tag: 5.7.20
  containerPort: 3306
  volumeMounts:
    name: mysql-storage
    mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    name: mysql-storage
    accessModes: ReadWriteOnce
    storage: 1Gi
  service:
    name: chat-service-db
    type: ClusterIP
    port: 3306
    targetPort: 3306
  secret:
    name: db-secret

chatService:
  name: chat-service
  namespace: my-app-namespace-3
  replicas: 1
  selector:
    app: chat-service
  containerName: chat-service
  image:
    repository: imzainazm/chat-service
    tag: latest
  containerPort: 7100
  service:
    name: chat-service
    type: ClusterIP
    port: 7100
    targetPort: 7100

namespace: my-app-namespace-3

phpmyadmin:
  name: phpmyadmin
  namespace: my-app-namespace-3
  replicas: 1
  containerName: phpmyadmin
  image:
    repository: phpmyadmin/phpmyadmin
    tag: latest
  containerPort: 80
  volumeMounts:
    mountPath: /etc/phpmyadmin/config.user.inc.php
    subPath: phpmyadmin-config.user.inc.php
  volumes:
    configMap:
      name: app-config
      items:
        key: phpmyadmin-config.user.inc.php
        path: phpmyadmin-config.user.inc.php
  service:
    name: phpmyadmin-service
    type: NodePort
    port: 80
    targetPort: 80
    nodePort: 32002
  env:
    mysqlRootPasswordSecretName: db-secret
    mysqlRootPasswordSecretKey: MYSQL_ROOT_PASSWORD

usersServiceDb:
  statefulsetName: users-service-db
  replicaCount: 1
  selector:
    app: users-service-db
  image:
    repository: mysql
    tag: 5.7.20
  containerPort: 3306
  volumeMounts:
    mountPath: /var/lib/postgresql/data
  volumeClaim:
    accessMode: ReadWriteOnce
    storage: 1Gi
  service:
    name: users-service-db
  ports:
    port: 3306
    targetPort: 3306
  type: ClusterIP

service:
  name: users-service-db
  selector:
    app: users-service-db
  ports:
    port: 3306
    targetPort: 3306
  type: ClusterIP

usersService:
  deployment:
    name: users-service
    namespace: my-app-namespace-3
    replicas: 1
    selector:
      app: users-service
    containerName: users-service
    image:
      repository: imzainazm/users-service
      tag: latest
    containerPort: 7101
  service:
    name: users-service
    namespace: my-app-namespace-3
    selector:
      app: users-service
    ports:
      port: 7101
      targetPort: 7101
    type: ClusterIP
