apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.chatServiceDb.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "{{ .Values.chatServiceDb.service.name }}"
  replicas: {{ .Values.chatServiceDb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.chatServiceDb.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.chatServiceDb.selector.app }}
    spec:   
      containers:
      - name: {{ .Values.chatServiceDb.containerName }}
        image: {{ .Values.chatServiceDb.image.repository }}:{{ .Values.chatServiceDb.image.tag }}
        ports:
        - containerPort: {{ .Values.chatServiceDb.containerPort }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.chatServiceDb.secret.name }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.chatServiceDb.secret.name }}
              key: MYSQL_DATABASE
        volumeMounts:
        - name: {{ .Values.chatServiceDb.volumeMounts.name }}
          mountPath: {{ .Values.chatServiceDb.volumeMounts.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.chatServiceDb.volumeClaimTemplates.name }}
    spec:
      accessModes: [ "{{ .Values.chatServiceDb.volumeClaimTemplates.accessModes }}" ]
      resources:
        requests:
          storage: {{ .Values.chatServiceDb.volumeClaimTemplates.storage }}

          
