apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.phpmyadmin.service.name }}
  namespace: {{ .Values.phpmyadmin.namespace }}
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  selector:
    app: {{ .Values.phpmyadmin.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.phpmyadmin.service.port }}
      targetPort: {{ .Values.phpmyadmin.service.targetPort }}
      nodePort: {{ .Values.phpmyadmin.service.nodePort }}
