apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.usersService.deployment.name }}
  namespace: {{ .Values.usersService.deployment.namespace }}
spec:
  replicas: {{ .Values.usersService.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.usersService.deployment.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.usersService.deployment.selector.app }}
        {{- range $key, $value := .Values.usersService.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.usersService.deployment.containerName }}
        image: {{ .Values.usersService.deployment.image.repository }}:{{ .Values.usersService.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.usersService.deployment.containerPort }}
